# Generated by Django 5.0.12 on 2025-03-18 12:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_genericpage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('image', 1), ('paragraph', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
