# Generated by Django 5.0.12 on 2025-03-22 08:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_genericpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('image', 1), ('paragraph', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'template': 'heading_block.html'}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
